//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventeterAppAlpha.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventsterDBEntities : DbContext
    {
        public EventsterDBEntities()
            : base("name=EventsterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Userdata> Userdatas { get; set; }
    
        public virtual ObjectResult<Nullable<int>> spCountDistinctLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spCountDistinctLocations");
        }
    
        public virtual ObjectResult<GetCountOfEvents_Result> GetCountOfEvents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountOfEvents_Result>("GetCountOfEvents");
        }
    
        public virtual ObjectResult<Nullable<int>> spCountTeams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spCountTeams");
        }
    
        public virtual ObjectResult<Nullable<int>> spCountUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spCountUsers");
        }
    
        public virtual ObjectResult<Nullable<int>> spDistinctCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spDistinctCount");
        }
    
        public virtual int spInnerJoinEvent_and_Location()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInnerJoinEvent_and_Location");
        }
    
        public virtual int spInnerJoinEvent_and_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInnerJoinEvent_and_User");
        }
    
        public virtual int spInnerJoinSport_and_Location()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInnerJoinSport_and_Location");
        }
    
        public virtual int spLeftOuterJoinSport_Team()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLeftOuterJoinSport_Team");
        }
    
        public virtual ObjectResult<spLeftOuterJoinUser_Team_Result> spLeftOuterJoinUser_Team()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLeftOuterJoinUser_Team_Result>("spLeftOuterJoinUser_Team");
        }
    
        public virtual int spRightOuterJoinTeam_Event()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRightOuterJoinTeam_Event");
        }
    
        public virtual ObjectResult<spUserList_Result> spUserList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUserList_Result>("spUserList");
        }
    }
}
