//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventeterAppAlpha.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventsterDBEntities : DbContext
    {
        public EventsterDBEntities()
            : base("name=EventsterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Userdata> Userdatas { get; set; }
    
        public virtual ObjectResult<GetCountDistinctLocations_Result> GetCountDistinctLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountDistinctLocations_Result>("GetCountDistinctLocations");
        }
    
        public virtual ObjectResult<GetCountOfEvents_Result> GetCountOfEvents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountOfEvents_Result>("GetCountOfEvents");
        }
    
        public virtual ObjectResult<GetCountTeams_Result> GetCountTeams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountTeams_Result>("GetCountTeams");
        }
    
        public virtual ObjectResult<GetCountUsers_Result> GetCountUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountUsers_Result>("GetCountUsers");
        }
    
        public virtual ObjectResult<GetDistinctCount_Result> GetDistinctCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDistinctCount_Result>("GetDistinctCount");
        }
    
        public virtual ObjectResult<GetInnerJoinEvent_and_Location_Result> GetInnerJoinEvent_and_Location()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInnerJoinEvent_and_Location_Result>("GetInnerJoinEvent_and_Location");
        }
    
        public virtual ObjectResult<GetInnerJoinEvent_and_User_Result> GetInnerJoinEvent_and_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInnerJoinEvent_and_User_Result>("GetInnerJoinEvent_and_User");
        }
    
        public virtual ObjectResult<GetInnerJoinSport_and_Location_Result> GetInnerJoinSport_and_Location()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInnerJoinSport_and_Location_Result>("GetInnerJoinSport_and_Location");
        }
    
        public virtual int spLeftOuterJoinSport_Team()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLeftOuterJoinSport_Team");
        }
    
        public virtual ObjectResult<GetLeftOuterJoinUser_Team_Result> GetLeftOuterJoinUser_Team()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLeftOuterJoinUser_Team_Result>("GetLeftOuterJoinUser_Team");
        }
    
        public virtual ObjectResult<GetRightOuterJoinTeam_Event_Result> GetRightOuterJoinTeam_Event()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRightOuterJoinTeam_Event_Result>("GetRightOuterJoinTeam_Event");
        }
    
        public virtual ObjectResult<GetUserList_Result> GetUserList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserList_Result>("GetUserList");
        }
    
        public virtual int spUpdateEvent(string eventTitle, string hostName, Nullable<System.DateTime> eventDate, string phoneNumber, string description, string email)
        {
            var eventTitleParameter = eventTitle != null ?
                new ObjectParameter("EventTitle", eventTitle) :
                new ObjectParameter("EventTitle", typeof(string));
    
            var hostNameParameter = hostName != null ?
                new ObjectParameter("HostName", hostName) :
                new ObjectParameter("HostName", typeof(string));
    
            var eventDateParameter = eventDate.HasValue ?
                new ObjectParameter("EventDate", eventDate) :
                new ObjectParameter("EventDate", typeof(System.DateTime));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateEvent", eventTitleParameter, hostNameParameter, eventDateParameter, phoneNumberParameter, descriptionParameter, emailParameter);
        }
    
        public virtual ObjectResult<GetInnerJoinSport_Team_Result> GetInnerJoinSport_Team()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInnerJoinSport_Team_Result>("GetInnerJoinSport_Team");
        }
    
        public virtual ObjectResult<GetEventsList_Result> GetEventsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventsList_Result>("GetEventsList");
        }
    
        public virtual ObjectResult<GetLocationList_Result> GetLocationList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationList_Result>("GetLocationList");
        }
    
        public virtual ObjectResult<GetSportsList_Result> GetSportsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSportsList_Result>("GetSportsList");
        }
    
        public virtual ObjectResult<GetTeamList_Result> GetTeamList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamList_Result>("GetTeamList");
        }
    }
}
