//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventeterAppAlpha.Models
{
    using System;
    
    public partial class GetInnerJoinEvent_and_User_Result1
    {
        public string EventTitle { get; set; }
        public string HostName { get; set; }
    }
}
