//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventeterAppAlpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationID { get; set; }
        public int EventID { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public int SportID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
